version: "3.3"
services:
  oracle:
    image: "switchboardlabs/node:${SBV2_ORACLE_VERSION:-dev-v2-07-11-22}" # https://hub.docker.com/r/switchboardlabs/node/tags
    network_mode: host
    restart: always
    secrets:
      - PAYER_SECRETS
    environment:
      - VERBOSE=1
      - LIVE=1
      - CLUSTER=${CLUSTER:-localnet}
      - HEARTBEAT_INTERVAL=30 # Seconds
      - ORACLE_KEY=7pqX6qEABdf9rUeLW7YXZn3hqBMqAxZMgTKY8xaXrkaF
    #  - RPC_URL=${RPC_URL}
secrets:
  PAYER_SECRETS:
    file: /Users/rchen/work/swim/swim-monorepo/packages/solana-contracts/src/__tests__/test_wallet.json
