[features]
seeds = true
skip-lint = false

[programs.localnet]
#two_pool = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
two_pool = "8VNVtWUae4qMe535i4yL1gD3VTo8JhcfFEygaozBq8aM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./sdk/tests/pool_test.json"

[scripts]
test = "yarn run ts-mocha -p ./sdk/tests/tsconfig.json -t 1000000 sdk/tests/**/*.ts"
#initialize_pool = "yarn run scripts:build && sdk/scripts/dist/initialize_pool.js"
initialize_pool = "yarn run ts-node sdk/scripts/initialize_pool.ts"
