[features]
seeds = true
skip-lint = false

[programs.localnet]
#two_pool = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
two_pool = "8VNVtWUae4qMe535i4yL1gD3VTo8JhcfFEygaozBq8aM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./sdk/tests/pool_test.json"

[scripts]
test = "yarn run ts-mocha -p ./sdk/tests/tsconfig.json -t 1000000 sdk/tests/**/*.ts"
initialize_pool = "yarn run sdk:build && yarn run ts-node sdk/scripts/initialize_pool.ts"

[test.validator]
url="https://api.devnet.solana.com"

# load mpl-token-metadata program from devnet
[[test.validator.clone]]
address="metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
