name: "Verify core build"
on:
  pull_request:
    paths:
      - "packages/core/**.ts"
      - "packages/core/**.json"
      - "yarn.lock"
  push:
    branches:
      - master

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml
    with:
      workingDirectory: ./packages/core
