name: "Deploy UI to production"

on:
  push:
    # branches:
    #   - master

jobs:
  # verify:
  #   uses: ./.github/workflows/ui-verify.yaml

  production-deploy:
    runs-on: ubuntu-latest

    # Allow only one concurrent deployment
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    # needs: [verify]

    env:
      # For a yet unknown reason, actions/cache for the 'apps/ui/build' folder makes that folder permanently missing.
      # Copy of 'apps/ui/build' to the $BUILD_CACHE_PATH fixes build, cache, and direct upload to Cloudflare.
      BUILD_CACHE_PATH: ~/.ui-build-cache
      ACTIONS_STEP_DEBUG: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          # This caches Yarn cache (yarn config get cacheFolder) but not node_modules
          # https://github.com/actions/setup-node/issues/325#issuecomment-1120962692
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable --network-timeout 180000

      - name: Get production environment variables from Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_SWIM_PAGES_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          # Get production environment variables from Cloudflare Pages
          # https://api.cloudflare.com/#pages-project-get-project
          # and append it to $GITHUB_ENV
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
          curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/swim-ui" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            --compressed |
            jq -r '.result.deployment_configs.production.env_vars | to_entries[] | "\(.key)=\(.value.value)"' > .env

      - name: Cache UI build directory
        uses: actions/cache@v3
        with:
          path: ${{ env.BUILD_CACHE_PATH }}
          key: ui-build-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}-${{ github.head_ref || github.ref_name }}
          restore-keys: |
            ui-build-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}-
            ui-build-${{ hashFiles('**/yarn.lock') }}-
            ui-build-

      - name: Build UI
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          # TODO: Don't skip source maps deployment to Sentry before merging to master
          SKIP_SENTRY: "true"
          # Ignore missing optional dependencies of moralis we don't use ('@walletconnect/web3-provider', '@web3auth/web3auth', 'magic-sdk')
          CI: "false"
        run: |
          yarn release-ui

          cp -r apps/ui/build/. ${{ env.BUILD_CACHE_PATH }}
          ls -laR ${{ env.BUILD_CACHE_PATH }}

      - name: Direct upload built UI to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_SWIM_PAGES_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          npx --yes wrangler@2 pages publish ${{ env.BUILD_CACHE_PATH }} --project-name=test-direct-upload-swim-ui --branch=${{ github.head_ref || github.ref_name }}
