name: "Verify eslint-config build"
on:
  pull_request:
    paths:
      - "packages/eslint-config/**.cjs"
      - "packages/eslint-config/**.json"
  push:
    branches:
      - master

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml
    with:
      workingDirectory: ./packages/eslint-config
      skipTest: true
      skipTypecheck: true
