name: "Verify eslint-config build"
on:
  pull_request:
    paths:
      - "packages/eslint-config/**"
      - ".github/workflows/verify.yaml"
      - ".github/workflows/eslint-config-verify.yaml"
  push:
    branches:
      - master

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml
    with:
      workingDirectory: ./packages/eslint-config
      skipTest: true
      skipTypecheck: true
