name: "Verify pool-math build"
on:
  pull_request:
    paths:
      - "packages/pool-math/**"
      - ".github/workflows/pool-math-verify.yaml"
      - ".github/workflows/verify.yaml"
      - "yarn.lock"
  push:
    branches:
      - master

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml
    with:
      workingDirectory: ./packages/pool-math
