name: "Verify pool-math build"
on:
  pull_request:
    paths:
      - "packages/pool-math/**.ts"
      - "packages/pool-math/**.json"
      - "yarn.lock"
  push:
    branches:
      - master

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml
    with:
      workingDirectory: ./packages/pool-math
