name: "Verify redeemer build"
on:
  pull_request:
    paths:
      - "packages/redeemer/**.ts"
      - "packages/redeemer/**.json"
      - "yarn.lock"
  push:
    branches:
      - master

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml
    with:
      workingDirectory: ./packages/redeemer
      buildDependenciesForPackage: "@swim-io/redeemer"
