name: "Verify solana build"
on:
  pull_request:
    paths:
      - "packages/solana/**"
      - ".github/workflows/solana-verify.yaml"
      - ".github/workflows/verify.yaml"
      - "yarn.lock"
  push:
    branches:
      - master

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml
    with:
      workingDirectory: ./packages/solana
      buildDependenciesForPackage: "@swim-io/solana"
