name: "Verify solana build"
on:
  pull_request:
    paths:
      - "packages/solana/**.ts"
      - "packages/solana/**.json"
  push:
    branches:
      - master

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml
    with:
      workingDirectory: ./packages/solana
      buildDependenciesForPackage: "@swim-io/solana"
