name: "Verify swim build"
on:
  pull_request:
    paths:
      - "packages/swim/**"
      - ".github/workflows/swim-verify.yaml"
      - ".github/workflows/verify.yaml"
      - "yarn.lock"
  push:
    branches:
      - master

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml
    with:
      workingDirectory: ./packages/swim
      buildDependenciesForPackage: "@swim-io/swim"
