name: "Verify token-projects build"
on:
  pull_request:
    paths:
      - "packages/token-projects/**/*.{ts,json}"
      - ".github/workflows/token-projects-verify.yaml"
      - ".github/workflows/verify.yaml"
      - "yarn.lock"
  push:
    branches:
      - master

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml
    with:
      workingDirectory: ./packages/token-projects
      buildDependenciesForPackage: "@swim-io/token-projects"
