name: "Verify tsconfig build"
on:
  pull_request:
    paths:
      - "packages/tsconfig/**.json"
  push:
    branches:
      - master

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml
    with:
      workingDirectory: ./packages/tsconfig
      skipTest: true
      skipTypecheck: true
