name: "Verify utils build"
on:
  pull_request:
    paths:
      - "packages/utils/**/*.{ts,json}"
      - ".github/workflows/utils-verify.yaml"
      - ".github/workflows/verify.yaml"
      - "yarn.lock"
  push:
    branches:
      - master

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml
    with:
      workingDirectory: ./packages/utils
