[package]
name = "pool-lib"
version = "1.0.0"
edition = "2018"
homepage = "https://swim.io"
keywords = ["solana", "swim", "program", "pool"]
license = "BUSL-1.1"


[features]
no-entrypoint = []
test-bpf = []
fuzz = ["arbitrary", "roots"]


[dependencies]
#solana related dependencies
# loosely pinned to same version as anchor
solana-program = "1.10.33"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }

#anchor
anchor-lang = { version = "0.25.0", features = ["init-if-needed"] }
anchor-spl = "0.25.0"

#numerics
# This must be pinned to 0.9.1 until Solana's Rust fork supports Rust >=1.56.1
uint = { version = "=0.9.1", default-features = false }
rust_decimal = {version = "1.24", features = [ "maths" ] }
rust_decimal_macros = "1.24"

#error handling
thiserror = "1.0"
num-traits = "0.2"
num-derive = "0.3"

#security_txt
solana-security-txt = "1.0.1"

#misc
arrayvec = "0.7.2"


arbitrary = { version = "1.1.3", features = ["derive"], optional = true}
honggfuzz = {version = "0.5.54", optional = true }
roots = { version = "0.0.7", optional = true }
